@startuml Mie Ayam Wengi 57 UseCase
left to right direction
skinparam packageStyle rectangle
skinparam roundcorner 10
skinparam theme cerulean-outline

skinparam usecase {
  BackgroundColor #f8f9fa
  BorderColor #000000
  FontSize 13
  FontName "Helvetica"
}
skinparam actorStyle stickman

title **Use Case Diagram - Pemesanan & Pengelolaan Mie Ayam "Wengi 57"**

actor "User" as User
actor "Admin" as Admin

rectangle "Sistem Informasi Pemesanan Mie Ayam Wengi 57" {
  
  usecase "Melihat Daftar Menu" as U1
  usecase "Tentang Kami" as U2
  usecase "Menu Kami" as U4
  usecase "Melakukan Pembelian Makanan" as U3
  usecase "Melakukan Pembayaran" as U5_pay
  usecase "Login" as U5
  usecase "Logout" as U6
  usecase "Mengelola Menu Mie Ayam\n(CRUD)" as U7
  usecase "Mengelola Pesanan Pelanggan\n(Ubah Status/Batal)" as U8
  usecase "Dashboard" as UDashboard
  usecase "Riwayat Pesanan" as URiwayat
}

' --- Hubungan aktor ke use case ---
User --> U1
User --> U2
User --> U3
User --> U5_pay

Admin --> U6
Admin --> U7
Admin --> U8
Admin --> U5
Admin --> UDashboard
Admin --> URiwayat


' --- Relasi include ---
U6 ..> U4 : <<include>>
U7 ..> U4 : <<include>>
U5 ..> U4 : <<extend>>

@enduml
